name: QOTD Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 10 AM Eastern Time (UTC -4)

jobs:
  run-qotd:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install python-dotenv requests
    - name: Restore Cache
      uses: actions/cache@v3
      id: cache-used-questions
      with:
        path: usedQuestions.json
        key: used-questions-${{ runner.os }}
    - name: Display usedQuestions.json
      run: cat usedQuestions.json || echo "No used questions yet"
    - name: Run QOTD Script
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: python qotd.py
    - name: Update Cache
      if: steps.cache-used-questions.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: usedQuestions.json
        key: used-questions-${{ runner.os }}
